### PR TITLE
@PlatformIO Library Registry manifest file

### PR DESCRIPTION
**Pull request by valeros**
Description
* This library in Web Registry: http://platformio.org/lib/show/222/AppleMidi
* Specification: [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html)
* Library Manager: http://docs.platformio.org/en/latest/librarymanager/index.html

### CODE REVIEW

**Comment by lathoub** [comment]
Dear valeros,

Thank you for suggesting to link to the AppleMIDI Arduino lib from PlatformIO. I just have a look and Platform IO looks real cool. Great job.

I do however have an issue with adding "yet-another-manifest-file" - a manifest file for the core Arduino platform is available and very easy to parse and transform to the PlatformIO preferred format. Maintaining n-manifest file for n IDE's is not what I want to do (and clutters the root directory)

Needless to say I encourage your initiative (well done and congrats with the nomination), I also want to encourage you to support the manifest file of the de facto Arduino IDE.

Best regards,

**Comment by ivankravets** [comment]
Dear @lathoub 

We are not "Yet another IDE". PlatformIO is cross platform and independent ecosystem with own Build System and Library Manager. We don't depend on Arduino IDE or Java. PlatformIO IDE it's just an example how should look the next generation IDE for IoT development. We allow users to choose other professional IDE http://docs.platformio.org/en/latest/ide.html

Rgds.

**Comment by ivankravets** [comment]
Please take a look on my answer for @ladyada https://github.com/platformio/platformio/issues/499#issuecomment-192637206

**Comment by lathoub** [comment]
Dear Ivan

I hear your point, but do not agree. I do not want to maintain every manifest file for every IDE/Platform/ecosystem (use your favorite term) that is out there.

to quote you: 
> This manifest is developed for PlatformIO ecosystem but can be used with any software/build system.

The same can be said for `library.properties`.
I'm apparently not the only one pushing back on the idea of adding (your) manifest file to libs (how great it might be) - its probably less effort to support `library.properties` in PlatformIO than to reply to this types of conversation.

Having said all that: all the best and good luck with PlatformIO

Best regards

**Comment by ivankravets** [comment]
Dear @lathoub,

We can't use this "properties" because it doesn't allow to specify library dependencies, framework compatibilities, own build flags, control for Build System and etc. I don't have any objections to Arduino's library.properties. The big problem here that we don't support only Arduino or things related to it. Developers require more professional manifest file where they can control whole build process, dependencies and etc.

> Having said all that: all the best and good luck with PlatformIO
Thanks, you too.

**Pull request closed without merging**
